name: Build and test Jextract

on:
  push:
    branches: [ master ]

  workflow_dispatch: # Keep workflow_dispatch

env:
  LLVM_HOME: /usr/lib/llvm-18

jobs:
  build-and-publish-linux-artifact:
    runs-on: ubuntu-latest # Set runs-on
    steps:
    - name: 'Check out repository'
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 1

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'

    - name: 'Check default Java version'
      shell: sh
      run: |
        java --version
        echo JAVA_HOME=$JAVA_HOME
        echo JDK_HOME=$JAVA_HOME

    - name: Install LLVM and Clang
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm clang libclang-dev llvm-dev

        clang --version
        echo "Clang installed in: $(which clang)"
        echo "LLVM_HOME is $LLVM_HOME"

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper

    - name: Build jextract artifact image
      run: |
        chmod +x ./gradlew
        ./gradlew -Pjdk_home="$JAVA_HOME" -Pllvm_home=${{ env.LLVM_HOME }} clean verify

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: jextract-linux-amd64
        path: build
        retention-days: 7
        overwrite: true
        include-hidden-files: true
